package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// #F id:gag85rik state_file.location
// #F id:b1nwn0gi state_file.structure
type LockFile struct {
	Spec  map[string]string // clause_id -> spec_hash
	Site  map[string]string // marker_id -> content_hash
	State map[string]string // marker_id:clause_id -> reviewed_spec_hash
}

func NewLockFile() *LockFile {
	return &LockFile{
		Spec:  make(map[string]string),
		Site:  make(map[string]string),
		State: make(map[string]string),
	}
}

func LockFilePath(specPath string) string {
	return filepath.Join(filepath.Dir(specPath), ".filament")
}

// #F id:kc1zl38h state_file.auto_generated

func ReadLockFile(path string) (*LockFile, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	lock := NewLockFile()
	section := ""
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = line[1 : len(line)-1]
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := parts[0]
		value := parts[1]
		switch section {
		case "spec":
			lock.Spec[key] = value
		case "site":
			lock.Site[key] = value
		case "state":
			lock.State[key] = value
		}
	}
	return lock, scanner.Err()
}

func WriteLockFile(path string, lock *LockFile) error {
	var b strings.Builder

	b.WriteString("# .filament — auto-generated by filament. Do not edit.\n\n")

	// #F id:hewrrmd3 state_file.sections.spec
	b.WriteString("[spec]\n")
	for _, k := range sortedKeys(lock.Spec) {
		b.WriteString(fmt.Sprintf("%s=%s\n", k, lock.Spec[k]))
	}

	// #F id:uzpjfbtw state_file.sections.site
	b.WriteString("\n[site]\n")
	for _, k := range sortedKeys(lock.Site) {
		b.WriteString(fmt.Sprintf("%s=%s\n", k, lock.Site[k]))
	}

	// #F id:5tc51mno state_file.sections.state
	b.WriteString("\n[state]\n")
	for _, k := range sortedKeys(lock.State) {
		b.WriteString(fmt.Sprintf("%s=%s\n", k, lock.State[k]))
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
